FROM node:20.12.0-alpine3.19

WORKDIR /user/src/app

COPY package.json package-lock.json turbo.json tsconfig.json ./

#TODO: we should get all the package.json from the each app and then run npm install and after that copy the source code

COPY apps ./apps
COPY packages ./packages

RUN npm install

RUN cd packages/db ** npx prisma generate && cd ../..

#TODO: Filter the build down to just one app
RUN npm run build

CMD ["npm", "run", "start-user-app"]
